Snorql Alerting
udaan-com/snorql pull request #77
Opened 2022-09-21 17:55 UTC by prajain12

Signed-off-by: Prakul Jain <prakul.jain@udaan.com>

## Motivation and Context

Alerting feature is currently missing in Snorql. Alerting will enable users to get alerts when certain threshold is crossed for a database.

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Backward compatibility

- [ ] snorql-extensions
- [x] snorql-framework

## How Has This Been Tested?

Tested locally

## Migration and deployment details (if appropriate)

NA

2022-10-21 12:19 UTC, lakshmi-udaan reviewed
How are we deciding on the SNAPSHOT version?
Can we address the detekt comments & if not can we remove the unnecessary ones?

2022-10-21 12:24 UTC, lokeshdevnani requested changes

2022-10-21 12:24 UTC, lokeshdevnani commented on snorql-framework/src/main/kotlin/com/udaan/snorql/framework/alerts/AlertsJob.kt
> +//            logger.info("Inside AlertsJob Class")
delete

2022-10-21 12:24 UTC, lokeshdevnani commented on snorql-extensions/src/main/kotlin/com/udaan/snorql/extensions/alerts/alert/ActiveQueriesAlert.kt
> +        }
```suggestion
            filteredQueryList = filteredQueryList.filter {
               it.cpuTime != null && it.cpuTime >= alertInput.cpuTimeThreshold
            }
        }
```

2022-10-21 12:30 UTC, prajain12 commented
> How are we deciding on the SNAPSHOT version? Can we address the detekt comments & if not can we remove the unnecessary ones?

SNAPSHOT version is a minor increase as these features will be rolled out in the next major release post incorporating all enhancements.
Working on detekt comments

2022-10-26 07:37 UTC, lokeshdevnani approved these changes
LGTM

2022-10-26 08:08 UTC, merged